---
title: "Initial analysis"
author: "X Matthijssen"
output: 
  html_document:
    toc: true
    theme: united
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),Sys.Date(),'.html')) })
---

```{r setup, echo = F, message = F, results = 'hide'}
# required packages 

if(!require(sirt)){install.packages("sirt"); library(sirt)}
if(!require(tidyverse)){install.packages("tidyverse"); library(tidyverse)}
if(!require(tidylog)){install.packages("tidylog"); library(tidylog)}
if(!require(devtools)){install.packages("devtools"); library(devtools)}
load_all()

# General setup 
rm(list=ls())
set.seed(121212)

# start timer 
starting_time <- proc.time()
```


# Data preperation 

## Read  data 

```{r}
load("I:/Promovendi_Annette/Xanthe/4. Analyse hele EAC/EAC-nieuwe-start/0. Data/Produced/Beforeimp 2019-01-16.RData")

```

## clean data 
```{r}

```


## Merge data 
```{r}

```

## Make variables 
```{r}
data <- data %>% mutate(inclusiejaar = format.Date(DAT1EBEZ,"%Y") %>% as.numeric) 


data <- data %>% mutate(
  TJC_conv = 0.56*sqrt(TJC28),
  SJC_conv = 0.28*sqrt(SJC28),
  ESR_conv = 0.70*logbse,
  GH_conv = 0.014*VASZACT
)
```

## Subset data 
```{r}

data<- data %>% filter(!(is.na(TJC_conv) & is.na(SJC_conv) & is.na(ESR_conv) & !is.na(GH_conv)))


data_base <- data %>% filter(BEZNR ==1)


```

# Functions

# Constants
```{r}
# intercepts will follow automaticly
lavmodel <- "
        F=~ ESR_conv+SJC_conv+TJC_conv+GH_conv
"
lavmodel_int <- "
        F=~ ESR_conv+SJC_conv+TJC_conv+GH_conv
          ESR_conv ~ 1
  SJC_conv ~ 1
  TJC_conv~ 1
  GH_conv ~ 1
"

moderator_grid <- unique(data$inclusiejaar) %>% as.numeric()
moderator_grid2 <- c(1995,2000,2005,2010,2015)
moderator_grid3 <- 1995:2015
bandwidths <- c(2,5,10,15)


```

# Analyses 
## Hilderbrandt
### bandwidths due to Hildebrand
```{r}
calculate_bandwidth <- function(n, sd, h){
  bw <- (h* sd )/ n^0.2
  return(bw)
}

# these would be the bandwidths based on the bandwidht factors in hilderbrandt et al
hildebrandt_bw <- calculate_bandwidth(n = nrow(data_base), 
                    sd = sd(data_base$inclusiejaar), 
                    h = c(1.1,2,3))

hildebrandt_bw

bandwidths <- c(bandwidths, hildebrandt_bw)

```


### permuation test model 


```{r, eval= FALSE}
pmod1 <-lsem.permutationTest(
 lsem.estimate(
    data_base,
    moderator = "inclusiejaar",
    moderator.grid = moderator_grid,
    lavmodel = lavmodel,
    h = 2,
    fit_measures = "aic"
  ),
  B = 1000
)

save(pmod1, file = paste("../output/", Sys.Date(), "pmod1.RData", sep = ""))

pmod2 <-lsem.permutationTest(
 lsem.estimate(
    data_base,
    moderator = "inclusiejaar",
    moderator.grid = moderator_grid,
    lavmodel = lavmodel_int,
    h = 2,
    fit_measures = "aic"
  ),
  B = 1000
)

save(pmod2, file = paste("../output/", Sys.Date(), "pmod2.RData", sep = ""))

```

### permutation load 
```{r}
load("H:/lsembandwidth/output/2020-04-16pmod1.RData")

summary(pmod1)

load("H:/lsembandwidth/output/2020-04-16pmod2.RData")

summary(pmod2)


```


## bandwidth analysis AIC 
Lower AIC is better 
```{r}

test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid,
  statistic = "AIC"
)


test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid2,
  statistic = "AIC"
)

test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid3,
  statistic = "AIC"
)




```


## bandwidth analysis CV
Higher log likelihood is better 
So lower negative number 
```{r}


test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid,
  statistic = "CV",
  silent = TRUE,
  K = 2
)

test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid2,
  statistic = "CV",
  silent = TRUE
)

test_bandwidths(
  data = data_base,
  lavmodel = lavmodel_int,
  bandwidthvector = bandwidths,
  moderator_name = "inclusiejaar",
  moderator_grid = moderator_grid3,
  statistic = "CV",
  silent = TRUE
)

```

# Summary 

# Session info

```{r}
sessionInfo() 

proc.time() - starting_time
```

